apiVersion: v1
kind: Pod
metadata: 
  name: pod-config 
  labels:
    Project: roboshop
    environment: dev
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: configmaps